messenger4j:
  appSecret: 367e0ebac0afc0976cbf5038175d7fb9
  verifyToken: test_token
  pageAccessToken: EAAD2UIRBBG4BAF9rJRGsTq7gIm09lLw8UjdMpeQeCY3faUdDbo9cOuIXGMQODMfwNUaANZCdcVYHK0v38tTb0ck37WA6zcGgybLaouwhs3aLMIupyGj8iHt0lRHZBmqgF0Uo2lIgWKzqLQ9BuQbM7JPYguC6l0FUBARkcbJAZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO