messenger4j:
  appSecret: fe2fd14eca55327f0810e1ef2366ad48
  verifyToken: test_token
  pageAccessToken: EAATmxQx1md4BACgFy4XUS7xiPGRCtiznGZCUUylaHRiiA0QUgiU3xF9nB3I8z9TGRPJsGZCKAERZCZB6Nuc5ErDktA70ldG1UrEGmnhlIQnHP9xvcS5eZCaF8dfaXthEFHkTGnZCPoVL05ZC21z7MxvzU56vqFah8bKjKZCAtiukCAZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO