messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAFA1AdgoCGN2HQfXbrzUnCclvqdWfql7ZB4XjJBrr2cANGZCEv631cilNTvJ1CSU67Sjiu2BdW5bONZCq3h7Y7rABmEFZBRDJ8O79E5b7LaeslcVDZCjcUxvgmnI9vTVPjbZCic8x9TyZAMa1jRJAsKamybpkb5kAZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO