messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAIWGUjyiTchkTgc1JZB3Afb4ePKEaVnJc8A4U1ZBg7e3n5hxPZAMNzvJj1GMRbTc4OszJVsyDdx2M5c2Pjx8EdwpaNDknwJN3V6LR5G7BeTKXEvCSrjAKrUvoZCYxiWtFZBqB7zup9hpyZB0ZASjhi0TKlaOy3w2QZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO