messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBADuX2Ck5F6fopkiSSTZAuL7Ey1EwvL3ZBZAKq2WGZA2PLAZBZCNOzYczuEtPvd12aq32TxVRjCmDYdMX8rmB5o7QZBt8rO5MAIamrGTNLOSVjfIa7IZAaTulSEjZA0wL6Rykz3wUHcQPO9zRk5ysd4jpS3fn77kcpZBwZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO