messenger4j:
  appSecret: fe2fd14eca55327f0810e1ef2366ad48
  verifyToken: test_token
  pageAccessToken: EAATmxQx1md4BAB8Vv6rRcHMtT26I6RSs25RNKk4lD8bBB4NHIfNdH4HpRZAAKgOEQ2C6d6ijBlVerpcZB4hUvgInbjIXQEpZBDZB5UYHDrqZC5GmRLMF99ZALzguXweKKfkMjUaAn0HZCuLgZAfLTXvt27KBxa44tJBw96jKuCaIEQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO