messenger4j:
  appSecret: 367e0ebac0afc0976cbf5038175d7fb9
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAEAr00E4QnsAglNZAyjSmxvmpiiJuwhg86PNSxX7hJ0KQYyTzKeXJ431uQsjfZC3MZAIgAHAljmfYyZADxDPRvvZBkz9MILDe9xjujLm2SM5C6zHchxTvNV2JUYs9y9BfAk7b3TERVZC1j9OItRkVfJoeXp6dyCgZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO