messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAEAr00E4QnsAglNZAyjSmxvmpiiJuwhg86PNSxX7hJ0KQYyTzKeXJ431uQsjfZC3MZAIgAHAljmfYyZADxDPRvvZBkz9MILDe9xjujLm2SM5C6zHchxTvNV2JUYs9y9BfAk7b3TERVZC1j9OItRkVfJoeXp6dyCgZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO