messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAGJZChZBzTuktscI8cIypCPVQGTZCRHix7S0uoBBYURk9bXUqGcp9AY3k6IzOq9K6QT6X6UcluCEMeaQbm3eavShz1RLfPTvDZBgwZC6bsAb1Oy7YJ8mf9eZByhJNijIaODPzIMrnx54Db6p92sbNxuFzaQlJUUgZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO