messenger4j:
  appSecret: fe2fd14eca55327f0810e1ef2366ad48
  verifyToken: test_token
  pageAccessToken: EAATmxQx1md4BABZAYYYuYCLhBRS2GrvmHyL7W3ZBjn30ks0SepMrHrHiYcZAbFRvHLnUfCIa5zL9Sx94kdpt4ib62f2K6ZAu0PGbKVU4w4UXEV4GcWufYadHIYEuNotUpTaaZB5jBzUzZAF4aocoJyZBekEBTT26KKtcqkVHYF6YQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO