messenger4j:
  appSecret: fe2fd14eca55327f0810e1ef2366ad48
  verifyToken: test_token
  pageAccessToken: EAATmxQx1md4BABO4rQhVEZCsZCBZAAgw6A2j5JLBrZCI8ZAfGZCo7ZBVEX3uZB11h7ZArUCZBDacv9ydeUs8TpoMTm9ZCe3LtYu0uMx9cDxbCZAO3BGZAV9lHSxib4Pxk6R8WGKwtbpyQCtgjPm9VnW5AbWzEfWvCO3bLeuTc3aMadUmAFQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO