messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBAKl0dBdnGJ1nI9iKA0wjhCE6btJELBTZCP2QkIfZArzO6jmYnxlbq3QkfMmsvqnXGZC5kN8vzJRtk6zgH7p7fdjnkXSjININJUW15tZBVXxfkS5RoWTQjNTXuKVeMCxPuW4CTABK8japCI4iLV6pE2R8tBXuLQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO