messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBADgjWk1d0QyswpZCB3NahVdxsYcBh43sxL6XhZB6EWUZAgUNLbiGq2Dx8eMSHZBfZB0cGPOrZAU3XzlmNsEnq8Q5wNQJ4PTvhn4cvSC5UfPmZAkslYqhxXyEyUl6Vb6Cvx3TKilZBalDk7g8pS2ZBRx9ddZBaiWtTO8QZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO