messenger4j:
  appSecret: fe2fd14eca55327f0810e1ef2366ad48
  verifyToken: test_token
  pageAccessToken: EAATmxQx1md4BAKw64ZBaq5Wmjuy9Q2uM6gzDeRX6PP8CykwZCkF7ONyDqcyDTsnXbZAa6ZC83Rgpbwf0ZBboYcnegyb8zGUVe6Hqooq9hdtOdHqZAWh1ej477f80nwyzDe0S4CE2yY8np8h1kZCNLi2wGLJRVajDcP5213YsXy1xgZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO