messenger4j:
  appSecret: 71297f638a90a84c32567d593ffb2574
  verifyToken: test_token
  pageAccessToken: EAATZA7z3Dm0kBALupDEvxDVbAaCxZAM9tAvapAKY0WXfZBJm9EdHxgZCwKtHqVpOkWMZA6pbDhsetl0nPDj8UZAnkhHEWDqTMqKzFX10MjsqqgB39G3O1YFuaVpXPJ0iCFYhvIXVSOtHTUUBb2cJ0zHK99T09dVXq2yxW9RoZAwIQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO